### ISSUE TITLE
2.0.0-nullsafety.2 - Null check operator used on a null value

### ISSUE THREAD

**Issue by nousath** [Stacked-Org/stacked#281]
Kindly check staticChild null not working getting error **{Null check operator used on a null value}**

**Comment by bats64mgutsi** [comment]
I'm getting the same error when running the stacked example. This the full error I'm getting:

```text
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...                 9,4s
                                                                        
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _CastError was thrown building ViewModelBuilder<NonReactiveViewModel>(dirty, state:
_ViewModelBuilderState<NonReactiveViewModel>#a8ba3):
Null check operator used on a null value

The relevant error-causing widget was:
  ViewModelBuilder<NonReactiveViewModel>
  file:///C:/Users/.../stacked/packages/stacked/example/lib/ui/nonreactive/nonreactive_view.dart:11:12

When the exception was thrown, this was the stack:
#0      _ViewModelBuilderState.build (package:stacked/src/state_management/view_model_builder.dart:148:67)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:4612:27)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4495:15)
#3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4474:5)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4658:11)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4469:5)
...     Normal element mounting (172 frames)
#179    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3541:14)
#180    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6094:32)
...     Normal element mounting (315 frames)
#495    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3541:14)
#496    Element.updateChild (package:flutter/src/widgets/framework.dart:3306:18)
#497    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1182:16)
#498    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1153:5)
#499    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1095:18)
#500    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2647:19)
#501    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1094:13)
#502    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:934:7)
#503    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:915:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
```

**Comment by FilledStacks** [comment]
@nousath we're working on it. I don't really know what the error is but we're trying to fix it. They types are inherited properly but I don't know why there's a miss match.

**Comment by FilledStacks** [comment]
This is fixed in the latest version
