### ISSUE TITLE
ShowDialog not working - Cupertino App

### ISSUE THREAD

**Issue by Abhis33** [Stacked-Org/stacked#427]
```Dart
    await _dialogService.showDialog(
      title: 'Test Dialog Title',
      description: 'Test Dialog Description',
      dialogPlatform: DialogPlatform.Cupertino,
    );
```

I'm using Cupertino App and I'm getting the below error -
```
E/flutter (17079): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: No MaterialLocalizations found.
E/flutter (17079): Navigator widgets require MaterialLocalizations to be provided by a Localizations widget ancestor.
E/flutter (17079): The material library uses Localizations to generate messages, labels, and abbreviations.
E/flutter (17079): To introduce a MaterialLocalizations, either use a MaterialApp at the root of your application to include them automatically, or add a Localization widget with a MaterialLocalizations delegate.
E/flutter (17079): The specific widget that could not find a MaterialLocalizations ancestor was:
E/flutter (17079):   Navigator-[LabeledGlobalKey<NavigatorState>#e3dad]
E/flutter (17079): The ancestors of this widget were:
E/flutter (17079):   DefaultTextStyle
E/flutter (17079):   CustomPaint
E/flutter (17079):   Banner
E/flutter (17079):   CheckedModeBanner
E/flutter (17079):   Title
E/flutter (17079):   Directionality
E/flutter (17079):   _LocalizationsScope-[GlobalKey#00fa3]
E/flutter (17079):   Semantics
E/flutter (17079):   Localizations
E/flutter (17079):   MediaQuery
E/flutter (17079):   _MediaQueryFromWindow
E/flutter (17079):   _FocusMarker
E/flutter (17079):   Focus
E/flutter (17079):   _FocusTraversalGroupMarker
E/flutter (17079):   FocusTraversalGroup
E/flutter (17079):   _ActionsMarker
E/flutter (17079):   Actions
E/flutter (17079):   _ShortcutsMarker
E/flutter (17079):   Semantics
E/flutter (17079):   _FocusMarker
E/flutter (17079):   Focus
E/flutter (17079):   Shortcuts
E/flutter (17079):   UnmanagedRestorationScope
E/flutter (17079):   RestorationScope
E/flutter (17079):   UnmanagedRestorationScope
E/flutter (17079):   RootRestorationScope
E/flutter (17079):   WidgetsApp-[GlobalObjectKey _CupertinoAppState#2d33a]
E/flutter (17079):   Builder
E/flutter (17079):   HeroControllerScope
E/flutter (17079):   IconTheme
E/flutter (17079):   _InheritedCupertinoTheme
E/flutter (17079):   CupertinoTheme
E/flutter (17079):   CupertinoUserInterfaceLevel
E/flutter (17079):   ScrollConfiguration
E/flutter (17079):   CupertinoApp
E/flutter (17079):   MyApp
E/flutter (17079):   [root]
E/flutter (17079): #0      debugCheckHasMaterialLocalizations.<anonymous closure> (package:flutter/src/material/debug.dart:71:7)
E/flutter (17079): #1      debugCheckHasMaterialLocalizations (package:flutter/src/material/debug.dart:91:4)
E/flutter (17079): #2      ExtensionDialog.dialog (package:get/get_navigation/src/extension_navigation.dart:225:12)
E/flutter (17079): #3      DialogService._showDialog (package:stacked_services/src/dialog/dialog_service.dart:112:16)
E/flutter (17079): #4      DialogService.showDialog (package:stacked_services/src/dialog/dialog_service.dart:76:14)
E/flutter (17079): #5      ProductViewModel.showDialogs (package:afk/ui/product/view_model.dart:12:26)
E/flutter (17079): #6      ProductView.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:afk/ui/product/view.dart:147:37)
E/flutter (17079): #7      ProductView.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:afk/ui/product/view.dart:146:40)
E/flutter (17079): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (17079): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:607:11)
E/flutter (17079): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
E/flutter (17079): #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
E/flutter (17079): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter (17079): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93:12)
E/flutter (17079): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:138:9)
E/flutter (17079): #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
E/flutter (17079): #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:136:18)
E/flutter (17079): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:122:7)
E/flutter (17079): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:381:19)
E/flutter (17079): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:361:22)
E/flutter (17079): #20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
E/flutter (17079): #21     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:316:7)
E/flutter (17079): #22     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:280:5)
E/flutter (17079): #23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:238:7)
E/flutter (17079): #24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:221:7)
E/flutter (17079): #25     _rootRunUnary (dart:async/zone.dart:1370:13)
E/flutter (17079): #26     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (17079): #27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (17079): #28     _invoke1 (dart:ui/hooks.dart:180:10)
E/flutter (17079): #29     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:276:7)
E/flutter (17079): #30     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
E/flutter (17079):
```

I'm using the latest stacked and stacked_services. Any ideas on fixing it?

**Comment by hurbes** [comment]
Add this line to your `CupertinoApp`
```dart
 localizationsDelegates: [DefaultMaterialLocalizations.delegate],
```

**Comment by FilledStacks** [comment]
@Abhis33 closing this since it looked like it worked. Re-open if you still have the same problem
