### ISSUE TITLE
Stacked_theme : setStatusBarColorBuilder throws error.

### ISSUE THREAD

**Issue by calebdeji** [Stacked-Org/stacked#482]
Whenever I specify the statusBarColor with 
`statusBarColorBuilder: (theme) => theme!.backgroundColor`

An error is thrown

> Exception has occurred.
PlatformException (PlatformException(error, java.lang.Long cannot be cast to java.lang.Integer, null, java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
	at com.sameer.flutterstatusbarcolor.flutterstatusbarcolor.FlutterStatusbarcolorPlugin.onMethodCall(FlutterStatusbarcolorPlugin.kt:34)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by myklll** [comment]
@FilledStacks Same issue here.

**Comment by isaacadariku** [comment]
@calebdeji @mychell is `backgroundColor` part of your `ThemeData` ?

For example:
```
ThemeData(
backgroundColor: Colors.blue[300],
 ),
```

If not, you can add it to your List of ThemeData and try again.

**Comment by FilledStacks** [comment]
Make sure that value is not null

**Comment by calebdeji** [comment]
It's not null. I attached a direct color value instead of using the data from the theme parameter. Same thing.

**Comment by hurbes** [comment]
@calebdeji We can't reproduce this issue. Are you on the latest version 0.3.6?

**Comment by calebdeji** [comment]
Yes I am.

**Comment by calebdeji** [comment]
The error actually only happens on android, works fine with IOS.
