### ISSUE TITLE
Class 'NavigationServiceMock' has no instance method 'navigateTo' with matching arguments.

### ISSUE THREAD

**Issue by JeffryHermanto** [Stacked-Org/stacked#578]
I'm not sure how to get passed this error. I tap the CustomTextButton that navigates to GetStartedView, I get this error:

**Debug Console**
```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
Class 'NavigationServiceMock' has no instance method 'navigateTo' with matching arguments.
Receiver: Instance of 'NavigationServiceMock'
Tried calling: navigateTo<dynamic>("[/get-started-view]()", arguments: null, id: null,
preventDuplicates: true, parameters: null)
Found: navigateTo<Y0>(String, {dynamic arguments, int? id, bool preventDuplicates, Map<String,
String>? parameters}) => Future<Y0?>?

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core-patch[/object_patch.dart:38:5]())
#1      Mock.noSuchMethod (package:mocktail[/src/mocktail.dart:100:18]())
#2      NavigationServiceMock.navigateTo (package:stacked_services[/src/navigation_service.dart:187:15]())
#3      _OnboardingViewState._buildMulaiSekarangButton.<anonymous closure> (package:raya[/ui/views/onboarding/onboarding_view.dart:139:45]())
#4      CustomTextButton.build.<anonymous closure> (package:raya[/ui/shared/custom_text_button.dart:34:56]())
#5      _InkResponseState._handleTap (package:flutter[/src/material/ink_well.dart:989:21]())
#6      GestureRecognizer.invokeCallback (package:flutter[/src/gestures/recognizer.dart:198:24]())
#7      TapGestureRecognizer.handleTapUp (package:flutter[/src/gestures/tap.dart:608:11]())
#8      BaseTapGestureRecognizer._checkUp (package:flutter[/src/gestures/tap.dart:296:5]())
#9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter[/src/gestures/tap.dart:230:7]())
#10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter[/src/gestures/recognizer.dart:563:9]())
#11     PointerRouter._dispatch (package:flutter[/src/gestures/pointer_router.dart:94:12]())
#12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter[/src/gestures/pointer_router.dart:139:9]())
#13     _LinkedHashMapMixin.forEach (dart:collection-patch[/compact_hash.dart:539:8]())
#14     PointerRouter._dispatchEventToRoutes (package:flutter[/src/gestures/pointer_router.dart:137:18]())
#15     PointerRouter.route (package:flutter[/src/gestures/pointer_router.dart:123:7]())
#16     GestureBinding.handleEvent (package:flutter[/src/gestures/binding.dart:439:19]())
#17     GestureBinding.dispatchEvent (package:flutter[/src/gestures/binding.dart:419:22]())
#18     RendererBinding.dispatchEvent (package:flutter[/src/rendering/binding.dart:322:11]())
#19     GestureBinding._handlePointerEventImmediately (package:flutter[/src/gestures/binding.dart:374:7]())
#20     GestureBinding.handlePointerEvent (package:flutter[/src/gestures/binding.dart:338:5]())
#21     TestWidgetsFlutterBinding.handlePointerEventForSource.<anonymous closure> (package:flutter_test[/src/binding.dart:496:42]())
#22     TestWidgetsFlutterBinding.withPointerEventSource (package:flutter_test[/src/binding.dart:506:11]())
#23     TestWidgetsFlutterBinding.handlePointerEventForSource (package:flutter_test[/src/binding.dart:496:5]())
#24     WidgetTester.sendEventToBinding.<anonymous closure> (package:flutter_test[/src/widget_tester.dart:808:15]())
#25     WidgetTester.sendEventToBinding.<anonymous closure> (package:flutter_test[/src/widget_tester.dart:807:39]())
#28     TestAsyncUtils.guard (package:flutter_test[/src/test_async_utils.dart:71:41]())
#29     WidgetTester.sendEventToBinding (package:flutter_test[/src/widget_tester.dart:807:27]())
#30     TestGesture.up.<anonymous closure> (package:flutter_test[/src/test_pointer.dart:394:24]())
#31     TestGesture.up.<anonymous closure> (package:flutter_test[/src/test_pointer.dart:392:39]())
#34     TestAsyncUtils.guard (package:flutter_test[/src/test_async_utils.dart:71:41]())
#35     TestGesture.up (package:flutter_test[/src/test_pointer.dart:392:27]())
#36     WidgetController.tapAt.<anonymous closure> (package:flutter_test[/src/controller.dart:280:21]())
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)

Handler: "onTap"
Recognizer:
  TapGestureRecognizer#f6ec2
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: no matching nodes in the widget tree
  Actual: _WidgetTypeFinder:<exactly one widget with type "OnboardingView" (ignoring offstage
widgets): OnboardingView(dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#ba3ea]],
state: _OnboardingViewState#6aa49)>
   Which: means one was found but none were expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> ([file:///Users/jeffryhermanto/Desktop/Raya/Mobile%20App/test/widgets/onboarding/onboarding_view_test.dart:27:7]())
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  [file:///Users/jeffryhermanto/Desktop/Raya/Mobile%20App/test/widgets/onboarding/onboarding_view_test.dart]() line 27
The test description was:
  When 'Mulai Sekarang' button tapped should navigate to GetStartedView
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following message was thrown:
Multiple exceptions (2) were detected during the running of the current test, and at least one was
unexpected.
════════════════════════════════════════════════════════════════════════════════════════════════════
Test failed. See exception logs above.
The test description was: When 'Mulai Sekarang' button tapped should navigate to GetStartedView

✖ OnboardingViewTest - When 'Mulai Sekarang' button tapped should navigate to GetStartedView
Exited (1) 
```

**test_setup.dart**
```
import 'package:dio/dio.dart';
import 'package:dio/dio.dart' as dio;
import 'package:flutter/material.dart';
import 'package:mocktail/mocktail.dart';
import 'package:raya/application/app/app.locator.dart';
import 'package:raya/infrastructure/apis/register_api.dart';

import 'package:stacked_services/stacked_services.dart';

class DioMock extends Mock implements Dio {}

class ResponseMock extends Mock implements dio.Response {}

class DioErrorMock extends Mock implements DioError {}

class NavigationServiceMock extends Mock implements NavigationService {}

class DialogServiceMock extends Mock implements DialogService {}

class MockNavigatorObserver extends Mock implements NavigatorObserver {}

class RegisterAPIMock extends Mock implements RegisterAPI {}

Dio getAndRegisterDioMock() {
  _removeRegistrationIfExists<Dio>();
  final dioMock = DioMock();
  locator.registerSingleton<Dio>(dioMock);

  return dioMock;
}

dio.Response getAndRegisterResponseMock() {
  _removeRegistrationIfExists<dio.Response>();
  final responseMock = ResponseMock();
  locator.registerSingleton<dio.Response>(responseMock);

  return responseMock;
}

DioError getAndRegisterDioErrorMock() {
  _removeRegistrationIfExists<DioError>();
  final dioErrorMock = DioErrorMock();
  locator.registerSingleton<DioError>(dioErrorMock);

  return dioErrorMock;
}

NavigationService getAndRegisterNavigationServiceMock() {
  _removeRegistrationIfExists<NavigationService>();
  final navigationServiceMock = NavigationServiceMock();
  locator.registerSingleton<NavigationService>(navigationServiceMock);

  return navigationServiceMock;
}

DialogService getAndRegisterDialogServiceMock() {
  _removeRegistrationIfExists<DialogService>();
  final dialogServiceMock = DialogServiceMock();
  locator.registerSingleton<DialogService>(dialogServiceMock);

  return dialogServiceMock;
}

RegisterAPI getAndRegisterEmployeesAPIMock() {
  _removeRegistrationIfExists<RegisterAPI>();
  final registerAPIMock = RegisterAPIMock();
  locator.registerSingleton<RegisterAPI>(registerAPIMock);

  return registerAPIMock;
}

void registerServices() {
  getAndRegisterDioMock();
  getAndRegisterResponseMock();
  getAndRegisterDioErrorMock();
  getAndRegisterNavigationServiceMock();
  getAndRegisterDialogServiceMock();
  getAndRegisterEmployeesAPIMock();
}

void unregisterServices() {
  locator.unregister<Dio>();
  locator.unregister<dio.Response>();
  locator.unregister<DioError>();
  locator.unregister<NavigationService>();
  locator.unregister<DialogService>();
  locator.unregister<RegisterAPI>();
}

void _removeRegistrationIfExists<T extends Object>() {
  if (locator.isRegistered<T>()) {
    locator.unregister<T>();
  }
}
```

**widget_test_util.dart**
```
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:provider/provider.dart';
import 'package:raya/application/app/app.router.dart';
import 'package:raya/application/enums/connectivity_status.dart';
import 'package:raya/application/services/connectivity_service.dart';
import 'package:stacked_services/stacked_services.dart';

class WidgetTestUtil {
  static Widget test(Widget widget) {
    return ScreenUtilInit(
      designSize: const Size(360, 640),
      builder: () => StreamProvider<ConnectivityStatus>(
        initialData: ConnectivityStatus.cellular,
        create: (context) =>
            ConnectivityService().connectionStatusController.stream,
        child: MaterialApp(
          home: widget,
          navigatorKey: StackedService.navigatorKey,
          onGenerateRoute: StackedRouter().onGenerateRoute,
        ),
      ),
    );
  }
}
```

**onboarding_view_test.dart**
```
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:raya/ui/views/get_started/get_started_view.dart';
import 'package:raya/ui/views/onboarding/onboarding_view.dart';

import '../../helpers/widget_test_util.dart';
import '../../helpers/test_setup.dart';

void main() {
  setUp(() {
    registerServices();
  });

  Widget createWidgetUnderTest() => WidgetTestUtil.test(const OnboardingView());

  group('OnboardingViewTest -', () {
    testWidgets(
        "When 'Mulai Sekarang' button tapped should navigate to GetStartedView",
        (WidgetTester tester) async {
      final mulaiSekarangButton =
          find.byKey(const ValueKey('mulaiSekarangButton'));

      await tester.pumpWidget(createWidgetUnderTest());
      await tester.tap(mulaiSekarangButton);
      await tester.pumpAndSettle();

      expect(find.byType(OnboardingView), findsNothing);
      expect(find.byType(GetStartedView), findsOneWidget);
    });
  });
}
```

**onboarding_view.dart**
```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:smooth_page_indicator/smooth_page_indicator.dart';
import 'package:stacked_services/stacked_services.dart';

import '../../../application/app/app.locator.dart';
import '../../../application/app/app.router.dart';
import '../../../application/app/constants/custom_color.dart';
import '../../../application/models/onboarding_model.dart';
import '../../shared/custom_text_button.dart';
import 'onboarding_utils.dart';

class OnboardingView extends StatefulWidget {
  const OnboardingView({Key? key}) : super(key: key);

  @override
  _OnboardingViewState createState() => _OnboardingViewState();
}

class _OnboardingViewState extends State<OnboardingView> {
  final _navigationService = locator<NavigationService>();
  late PageController _pageController;

  @override
  void initState() {
    super.initState();
    _pageController = PageController(initialPage: 0);
  }

  @override
  void dispose() {
    _pageController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final items = OnboardingUtils.getItemSplashScreen();

    return WillPopScope(
      onWillPop: () async {
        SystemChannels.platform.invokeMethod('SystemNavigator.pop');

        return true;
      },
      child: Scaffold(
        body: SafeArea(
          top: false,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            mainAxisAlignment: MainAxisAlignment.start,
            children: <Widget>[
              SizedBox(
                height: 500.h,
                child: PageView.builder(
                  controller: _pageController,
                  itemCount: items.length,
                  itemBuilder: (_, index) {
                    return _buildPageView(items[index]);
                  },
                ),
              ),
              _buildIndicator(items.length),
              const Spacer(),
              _buildMulaiSekarangButton(context),
            ],
          ),
        ),
      ),
    );
  }

  ListView _buildPageView(OnboardingModel item) {
    return ListView(
      padding: EdgeInsets.zero,
      physics: const NeverScrollableScrollPhysics(),
      children: [
        Container(
          height: 357.h,
          decoration: BoxDecoration(
            image: DecorationImage(
              image: AssetImage(item.imagePath ?? ''),
              fit: BoxFit.cover,
            ),
          ),
        ),
        Container(
          padding: EdgeInsets.symmetric(horizontal: 10.w),
          child: Column(
            children: [
              Container(
                padding: EdgeInsets.fromLTRB(16.w, 19.h, 16.w, 0),
                child: Text(
                  item.title ?? '',
                  style: Theme.of(context).textTheme.headline1,
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(16.w, 16.h, 16.w, 0),
                child: Text(
                  item.description ?? '',
                  style: Theme.of(context).textTheme.bodyText1?.copyWith(
                        color: CustomColor.textSecondary,
                        height: 1.4.h,
                      ),
                  textAlign: TextAlign.center,
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildIndicator(int itemsCount) {
    return SmoothPageIndicator(
      controller: _pageController,
      count: itemsCount,
      effect: const JumpingDotEffect(
        dotHeight: 6,
        dotWidth: 6,
        jumpScale: .7,
        verticalOffset: 15,
        dotColor: Colors.grey,
        activeDotColor: Colors.orange,
      ),
    );
  }

  Widget _buildMulaiSekarangButton(BuildContext context) {
    return Container(
      width: double.infinity,
      margin: EdgeInsets.fromLTRB(16.w, 0, 16.w, 16.h),
      child: CustomTextButton(
        key: const Key('mulaiSekarangButton'),
        label: 'Mulai Sekarang',
        onPressed: () => _navigationService.navigateTo(Routes.getStartedView),
      ),
    );
  }
}
```

**Comment by Eimen2018** [comment]
Try mocking navigateTo you can pass result to `getAndRegisterNavigationServiceMock({dynamic result})`
```  
when(service.navigateTo(
    any,
    arguments: anyNamed('arguments'),
    id: anyNamed('id'),
    parameters: anyNamed('parameters'),
    preventDuplicates: anyNamed('preventDuplicates'),
  )).thenAnswer((_) => Future.value(result)); ```
