### ISSUE TITLE
[stacked_services] Null check operator used on a null value in showCustomSnackbar

### ISSUE THREAD

**Issue by ryan-holder** [Stacked-Org/stacked#749]
The following exception is thrown when clicking on a custom snackbar without specifying the optional `onTap` parameter:

```
The following _CastError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack
#0      SnackbarService.showCustomSnackBar.<anonymous closure>
package:stacked_services/…/snackbar/snackbar_service.dart:191
#1      SnackbarController._getBodyWidget.<anonymous closure>.<anonymous closure>
package:get/…/snackbar/snackbar_controller.dart:236
#2      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:198
#3      TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:613
#4      BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:298
#5      BaseTapGestureRecognizer.acceptGesture
package:flutter/…/gestures/tap.dart:269
#6      GestureArenaManager.sweep
package:flutter/…/gestures/arena.dart:157
#7      GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:449
#8      GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:425
#9      RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:329
#10     GestureBinding._handlePointerEventImmediately
package:flutter/…/gestures/binding.dart:380
#11     GestureBinding.handlePointerEvent
package:flutter/…/gestures/binding.dart:344
#12     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:302
#13     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:285
#17     _invoke1 (dart:ui/hooks.dart:170:10)
#18     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#19     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 3 frames from dart:async)
Handler: "onTap"
```

Here's line 191 in `snackbar_service.dart`:

`onTap: (object) => onTap!(),`

And cheers for all your work on Stacked -- it's great

**Comment by jainmohit2001** [comment]
Same error faced. My firebase crashlytics is filled with these errors. Please resolve this issue.

**Comment by FilledStacks** [comment]
Could you post your `main.dart` code where you set the navigation key for your main navigator please. @ryan-holder and @jainmohit2001

**Comment by jainmohit2001** [comment]
```
MaterialApp(
          debugShowCheckedModeBanner: false,
          navigatorObservers: [
            StackedService.routeObserver,
            FirebaseAnalyticsObserver(analytics: FirebaseAnalytics.instance),
          ],
          theme: AppTheme.darkTheme,
          localizationsDelegates: AppLocalizations.localizationsDelegates,
          supportedLocales: AppLocalizations.supportedLocales,
          onGenerateRoute: StackedRouter().onGenerateRoute,
          navigatorKey: StackedService.navigatorKey,
        )
```

**Comment by ryan-holder** [comment]
```
class Startup extends StatelessWidget {
  const Startup({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return LifeCycleManager(
      child: ConnectivityManager(
        child: MaterialApp(
          title: 'app',
          theme: ThemeData(
            primarySwatch: Colors.green,
            visualDensity: VisualDensity.adaptivePlatformDensity,
          ),
          home: _initialRoute,
          navigatorKey: StackedService.navigatorKey,
          navigatorObservers: [StackedService.routeObserver],
          onGenerateRoute: CustomRouter.generateRoute,
        ),
      ),
    );
  }
}
```

**Comment by FilledStacks** [comment]
Thanks. And can you please also share the code you're using to show the snackbar.

**Comment by ryan-holder** [comment]
```
_snackbarService.showCustomSnackBar(
    variant: SnackbarType.example,
    message: "",
    duration: const Duration(seconds: 3),
);

```

Edit: I'm currently working around the issue by adding `onTap: () => {}`

**Comment by jainmohit2001** [comment]
```
 _snackbarService.showCustomSnackBar(
    message: 'Some error occurred! Please try again later',
    variant: SnackbarType.shiny,
);
```

**Comment by FilledStacks** [comment]
Thanks @ryan-holder and @jainmohit2001 

And the code where you register that custom variant + the builder code for the UI for the custom snackbar. 

It might be something in that code that's breaking.

**Comment by jainmohit2001** [comment]
`setup_snackbar.dart`

```
enum SnackbarType { shiny }

void setupSnackbar() {
  final SnackbarService snackbarService = locator<SnackbarService>();

  snackbarService.registerCustomSnackbarConfig(
    variant: SnackbarType.shiny,
    config: SnackbarConfig(
      titleTextAlign: TextAlign.center,
      margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 20),
      icon: Image.asset(
        Images.snackBarStar,
        height: 16,
      ),
      titleTextStyle: AppTypography.textSm.copyWith(
        fontWeight: FontWeight.w500,
      ),
      backgroundColor: const Color(0xFF1D2939),
      borderRadius: 12000,
      boxShadows: const [
        BoxShadow(
          color: Color.fromRGBO(120, 209, 177, 0.24),
          offset: Offset(0, 0),
          spreadRadius: 0,
          blurRadius: 36,
        )
      ],
    ),
  );
}
```


`main.dart`

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await setupLocator();
  setupSnackbar();
  ...
}
```

**Comment by FilledStacks** [comment]
@jainmohit2001 does the work around above work. If you add onTap:() => {} does it still throw the error?

**Comment by jainmohit2001** [comment]
Yes, the above-mentioned workaround works. No error is thrown.

I think the null check being done, as pointed out by @ryan-holder is the issue.

**Comment by ryan-holder** [comment]
Here's the builder code @FilledStacks 

```
void setupCustomStackedUi() {
  final snackbarService = locator<SnackbarService>();

  final snackbarConfig = SnackbarConfig(
    textColor: Colors.black,
    backgroundColor: Colors.white,
    borderColor: appGreen,
    borderRadius: 20.0,
    borderWidth: 2.0,
    margin: const EdgeInsets.fromLTRB(20, 0, 20, 20),
    boxShadows: [const BoxShadow(color: Colors.grey, offset: Offset(3, 3), blurRadius: 9, spreadRadius: 1,)]
  );

  snackbarService.registerCustomSnackbarConfig(variant: SnackbarType.example, config: snackbarConfig);
}
```

**Comment by FilledStacks** [comment]
Awesome. Yeah I think it's the issue with the onTap. I'll add it to my list to look at soon when I get some time.

**Comment by ryan-holder** [comment]
Thanks @FilledStacks. Let me know if we can help with a PR or anything

**Comment by FilledStacks** [comment]
@ryan-holder that would be great. The PR would be basic. I think all we have to do is use `?` instead of `!` where the error is being thrown for the onTap. 

I'll schedule some time to look at it tonight incase you don't get to it. Let me know if you do. PR's would always be welcome.

**Comment by FilledStacks** [comment]
Fixed in [commit](https://github.com/FilledStacks/stacked/commit/2f4b31279636c5aa80d4625527a7f37d9b297472)

**Comment by FilledStacks** [comment]
Released in 0.9.8 please test @ryan-holder and @jainmohit2001

**Comment by ryan-holder** [comment]
Working for me, thanks. And apologies, I was commenting late last night where I am.

**Comment by FilledStacks** [comment]
No need for apologies @ryan-holder Thank you for taking the time to provide enough details to find and fix the issue.
